namespace MonoBallFramework.Game.Engine.Core.Events;

/// <summary>
///     Base interface for all game events in the ECS event-driven architecture.
///     Events are messages that represent state changes or actions in the game world.
/// </summary>
/// <remarks>
///     Events flow through the EventBus system where handlers can subscribe to process them.
///     Events support object pooling via EventPool{T} to reduce allocations on hot paths.
///     When using pooling, call Reset() after renting from the pool.
///     See /docs/architecture/EventSystemArchitecture.md for event flow patterns.
/// </remarks>
public interface IGameEvent
{
    /// <summary>
    ///     Gets or sets the unique identifier for this event instance.
    ///     Auto-generated by base classes; reset by EventPool on Rent().
    /// </summary>
    Guid EventId { get; set; }

    /// <summary>
    ///     Gets or sets the timestamp when this event was created (UTC).
    ///     Auto-generated by base classes; reset by EventPool on Rent().
    /// </summary>
    DateTime Timestamp { get; set; }

    /// <summary>
    ///     Gets the type name of this event for logging and debugging.
    ///     Returns the concrete event type's simple name (e.g., "MovementStartedEvent").
    /// </summary>
    string EventType => GetType().Name;
}
